config/routes.rb
Rails.application.routes.draw do
  resources :luggage_tags do
    member do
      get :public
      post :report_missing
      match :report_found, via: [:get, :patch]
      post :report_ok
      get :qr
    end
  end
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/luggage_tag.rb
class LuggageTag < ApplicationRecord
  validates :origin, :destination, :start, :end, presence: true

  validates :found_by, :found_comment, presence: true, if: :report_found

  before_create :generate_uuid
  belongs_to :user

  attr_accessor :report_found

  def lost!
    update_column :lost_at, Time.now unless new_record?
  end

  def found!
    update_column :found_at, Time.now unless new_record?
  end

  def ok!
    update_column :ok_at, Time.now unless new_record?
  end


  private
  def generate_uuid
    begin
      generated_uuid = SecureRandom::uuid
    end while LuggageTag.exists? uuid: generated_uuid
    self['uuid'] = generated_uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :luggage_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    redirect_to(new_user_session_path, alert: 'Access denied, please log in') and return unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/luggage_tags_controller.rb
class LuggageTagsController < ApplicationController
  before_action :authenticate, except: [:public, :report_found, :qr]
  before_action :set_luggage_tag, only: [:show, :edit, :update, :destroy, :report_missing, :report_ok]
  before_action :generate_qr, only: [:public, :show, :qr]

  def public
    @luggage_tag = LuggageTag.find_by uuid: params[:id]
  end

  def report_missing
    @luggage_tag.lost! if @luggage_tag.ok_at.nil?
    redirect_to public_luggage_tag_url @luggage_tag.uuid
  end

  def report_found
    @luggage_tag = LuggageTag.find_by uuid: params[:id]
    if request.patch?
      @luggage_tag.report_found = true
      if @luggage_tag.update(luggage_tag_found_params)
        @luggage_tag.found! if @luggage_tag.ok_at.nil? && !@luggage_tag.lost_at.nil?
        redirect_to public_luggage_tag_url @luggage_tag.uuid and return
      end
    end
  end

  def qr
  end

  def report_ok
    @luggage_tag.ok!
    redirect_to public_luggage_tag_url @luggage_tag.uuid
  end


  # GET /luggage_tags
  # GET /luggage_tags.json
  def index
    @luggage_tags = current_user.luggage_tags.all
  end

  # GET /luggage_tags/1
  # GET /luggage_tags/1.json
  def show
  end

  # GET /luggage_tags/new
  def new
    @luggage_tag = current_user.luggage_tags.build
  end

  # GET /luggage_tags/1/edit
  def edit
  end

  # POST /luggage_tags
  # POST /luggage_tags.json
  def create
    @luggage_tag = current_user.luggage_tags.build(luggage_tag_params)

    respond_to do |format|
      if @luggage_tag.save
        format.html { redirect_to @luggage_tag, notice: 'Luggage tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /luggage_tags/1
  # PATCH/PUT /luggage_tags/1.json
  def update
    respond_to do |format|
      if @luggage_tag.update(luggage_tag_params)
        format.html { redirect_to @luggage_tag, notice: 'Luggage tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /luggage_tags/1
  # DELETE /luggage_tags/1.json
  def destroy
    @luggage_tag.destroy
    respond_to do |format|
      format.html { redirect_to luggage_tags_url, notice: 'Luggage tag was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_luggage_tag
      @luggage_tag = current_user.luggage_tags.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def luggage_tag_params
      params.require(:luggage_tag).permit(:user_id, :origin, :destination, :start, :end, :lost_at, :found_at, :ok_at)
    end
    def luggage_tag_found_params
      params.require(:luggage_tag).permit(:found_by, :found_comment)
    end

    def generate_qr
      @luggage_tag = LuggageTag.find_by uuid: params[:id]
      @luggage_tag = LuggageTag.find params[:id] if @luggage_tag.nil?
      url = public_luggage_tag_url @luggage_tag.uuid

      @qrcode = RQRCode::QRCode.new(url, :size => 10, :level => :h)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/luggage_tags_helper.rb
module LuggageTagsHelper
end

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
    <h4>
      <%= "#{pluralize(object.errors.count, "error")} prohibited this user from being saved:" %>
    </h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "LuggageAndFound" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">LuggageAndFound</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if current_user %>
            <ul class="nav navbar-nav">
              <li><%= link_to 'My Luggage Tags', luggage_tags_path %></li>
            </ul>
          <% end %>
          <p class="navbar-text navbar-right">
            <% if current_user %>
              Signed in as: <%= current_user.email %>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to 'Log in', new_user_session_path %>
              <%= link_to 'Sign up', new_user_registration_path %>
            <% end %>
          </p>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "#"  %></li>
              <li><%= link_to "Link2", "#"  %></li>
              <li><%= link_to "Link3", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/luggage_tags/_form.html.erb
<%= form_for @luggage_tag, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'errors', object: @luggage_tag %>
  <div class="form-group">
    <%= f.label :origin, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :origin, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :destination, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :destination, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_field :start, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_field :end, class: 'text_field form-control' %>
    </div>
  </div>
  <% unless @luggage_tag.new_record? %>
    <div class="form-group">
      <%= f.label :lost_at, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :lost_at, class: 'text_field form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :found_at, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :found_at, class: 'text_field form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :ok_at, class: 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.text_field :ok_at, class: 'text_field form-control' %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  luggage_tags_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/luggage_tags/edit.html.erb
<%- model_class = LuggageTag -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/luggage_tags/index.html.erb
<%- model_class = LuggageTag -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:origin) %></th>
      <th><%= model_class.human_attribute_name(:destination) %></th>
      <th><%= model_class.human_attribute_name(:start) %></th>
      <th><%= model_class.human_attribute_name(:end) %></th>
      <th><%= model_class.human_attribute_name(:lost_at) %></th>
      <th><%= model_class.human_attribute_name(:found_at) %></th>
      <th><%= model_class.human_attribute_name(:ok_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @luggage_tags.each do |luggage_tag| %>
      <tr>
        <td><%= luggage_tag.id %></td>
          <td><%= luggage_tag.user_id %></td>
          <td><%= luggage_tag.uuid %></td>
          <td><%= luggage_tag.origin %></td>
          <td><%= luggage_tag.destination %></td>
          <td><%= luggage_tag.start %></td>
          <td><%= luggage_tag.end %></td>
          <td><%= luggage_tag.lost_at %></td>
          <td><%= luggage_tag.found_at %></td>
          <td><%= luggage_tag.ok_at %></td>
        <td><%=l luggage_tag.created_at, format: :long %></td>
        <td>
          <%= link_to luggage_tag_path(luggage_tag), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_luggage_tag_path(luggage_tag), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to luggage_tag_path(luggage_tag), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_luggage_tag_path,
            class: 'btn btn-primary' %>

app/views/luggage_tags/new.html.erb
<%- model_class = LuggageTag -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/luggage_tags/public.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">Luggage tag: <%= @luggage_tag.uuid %></h1>
      </div>
      <div class="panel-body">
        <div class="jubmotron text-center">
          <div class="row">
            <div class="col-md-12 text-center qr-small">
              <%= @qrcode.as_html.html_safe %>
            </div>
            <h1>STATUS</h1>
            <% if @luggage_tag.lost_at && !@luggage_tag.found_at && !@luggage_tag.ok_at %>
              <span class="label label-danger">Reported missing on <%= @luggage_tag.lost_at.strftime '%d / %b / %Y at %H:%mi' %></span>
              <%= button_to 'Report found', report_found_luggage_tag_path(@luggage_tag.uuid), class: 'btn btn-success', method: :get %>

            <% elsif @luggage_tag.found_at && !@luggage_tag.ok_at %>
              <span class="label label-warning">Found on <%= @luggage_tag.found_at.strftime '%d / %b / %Y at %H:%mi' %></span>
              <% if current_user && @luggage_tag.user_id == current_user.id %>
                <div class="row">
                  <div class="col-md-12 text-center">
                    <%= button_to 'Report OK', report_ok_luggage_tag_path(@luggage_tag), class: 'btn btn-success' %>
                  </div>
                </div>
              <% end %>
            <% elsif @luggage_tag.ok_at %>
              <span class="label label-success">Reported OK <%= @luggage_tag.ok_at.strftime '%d / %b / %Y at %H:%mi' %></span>
            <% else %>
              <span class="label label-default">In progress</span>
              <% if current_user && @luggage_tag.user_id == current_user.id %>
                <div class="row">
                  <div class="col-md-2 col-md-offset-4">
                    <%= button_to 'Report missing', report_missing_luggage_tag_path(@luggage_tag), class: 'btn btn-danger' %>
                  </div>
                  <div class="col-md-2">
                    <%= button_to 'Report OK', report_ok_luggage_tag_path(@luggage_tag), class: 'btn btn-success' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4"><b>Origin</b></div>
          <div class="col-md-8"><%= @luggage_tag.origin%></div>
        </div>
        <div class="row">
          <div class="col-md-4"><b>Destination</b></div>
          <div class="col-md-8"><%= @luggage_tag.destination %></div>
        </div>
        <div class="row">
          <div class="col-md-4"><b>Start</b></div>
          <div class="col-md-8"><%= l @luggage_tag.start, format: '%d / %b / %Y' %></div>
        </div>
        <div class="row">
          <div class="col-md-4"><b>End</b></div>
          <div class="col-md-8"><%= l @luggage_tag.end, format: '%d / %b / %Y' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/luggage_tags/qr.html.erb
<div class="row">
  <div class="col-md-12 text-center qr">
    <%= @qrcode.as_html.html_safe %>
    <%= public_luggage_tag_url @luggage_tag.uuid%>
  </div>
</div>

app/views/luggage_tags/report_found.html.erb
<%= form_for @luggage_tag, url: report_found_luggage_tag_path, html: { class: 'form-horizontal' } do |f| %>
  <%= render 'errors', object: @luggage_tag %>
  <div class="form-group">
    <%= f.label :found_by, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :found_by, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :found_comment, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :found_comment, class: 'text_field form-control', rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit 'Report found', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/luggage_tags/show.html.erb
<%- model_class = LuggageTag -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="row">
  <div class="col-md-12 text-center qr">
    <%= link_to raw(@qrcode.as_html), qr_luggage_tag_url(@luggage_tag.uuid) %>
  </div>
</div>
<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:uuid) %></dt>
      <dd><pre class="prettyprint"><%= link_to @luggage_tag.uuid, public_luggage_tag_url(@luggage_tag.uuid) %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:origin) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.origin %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:destination) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.destination %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.start %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:end) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.end %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:lost_at) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.lost_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:found_at) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.found_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ok_at) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.ok_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:found_by) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.found_by %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:found_comment) %></dt>
      <dd><pre class="prettyprint"><%= @luggage_tag.found_comment %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              luggage_tags_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_luggage_tag_path(@luggage_tag), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              luggage_tag_path(@luggage_tag),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>